### PR TITLE
Fix multithreaded async pipes creation.

### PR DESCRIPTION
**Pull request by egorpugin**
See comments
https://github.com/klemens-morgenstern/boost-process/issues/98#issuecomment-325528819

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Thanks! Dumb question: is `atomic_uint64_t ` guaranteed to exist on a 32-bit system?

**Comment by egorpugin** [comment]
Not sure.
At first I wrote `std::atomic_size_t`, but changed it to match previous `unsigned long long`.

**Comment by egorpugin** [comment]
So, what's about this change?

**Comment by klemens-morgenstern** [comment]
Looks good, I'll merge it when the tests pass.

**Comment by egorpugin** [comment]
It seems working now. There are unrelated test fails.

**Comment by klemens-morgenstern** [comment]
Thanks man!

**Pull request merged**
