### PR TITLE
Pipe's fds are not closed after launch failure.

### PR DESCRIPTION
**Pull request by usrgth**

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Isn't that covered by setting `CLOEXEC` ? So on launch failure the subprocess exits thus closing the thing?

**Comment by usrgth** [comment]
`FD_CLOEXEC` covers this only if `execve` succeeds. Based on http://man7.org/linux/man-pages/man2/fcntl.2.html:

> If the FD_CLOEXEC bit is set, the file
       descriptor will automatically be closed during a successful
       execve(2).  (If the execve(2) fails, the file descriptor is left
       open.)

In this scenario we have from exception: 
> execve failed: No such file or directory

**Comment by klemens-morgenstern** [comment]
But if execve fails the child process exits in line 417 - the OS would then close the pipe because the process is no more. Am I wrong about that?

**Comment by usrgth** [comment]
Process created by fork has it's own fds. When process dies, they are closed, but those opened in parent process are not. Normally https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/posix/executor.hpp#L427 closes this fd, but in this scenario `_read_error` throws, so it's never executed. You can see that this actually happens, by running added here test without changes in the library itself.

**Comment by keith-bennett-gbg** [comment]
https://gist.github.com/keith-bennett-gbg/680d3e82a732471becfd97d171f5b7ea

```bash
$ g++ cloexec-does-not-close-in-parent.cpp 
$ ./a.out example-file
3       16      0       Success
fd appears to still be open even after execve should have failed in child
$ cat example-file
3       16      0       Success
no-such-executable      -1      2       No such file or directory
3       16      0       Success
```

`O_CLOEXEC` does not close the file descriptor _in the parent process_ (which was opened _before_ the call to `fork()`).

**Comment by klemens-morgenstern** [comment]
Does 8d2bd87 do the trick for you?

**Comment by usrgth** [comment]
Yes, this works.

**Pull request closed without merging**
