### PR TITLE
osx build fix

### PR DESCRIPTION
**Pull request by marton78**
Hi @klemens-morgenstern,

I have managed to build Boost.Process on OSX. I hope this helps!

M.

### CODE REVIEW

**Comment by klemens-morgenstern** [comment]
Awesome, thank you!

The removals of `detail::` are because they were redundant?

**Comment by marton78** [comment]
To be honest, I don't really understand why clang complained about `detail::`, it's clearly the correct namespace. It suggested me something along the lines of "detail::some_class not found in namespace, did you mean some_class?" with an option to auto-fix. That's what I clicked then.

**Comment by klemens-morgenstern** [comment]
Ok, that seems to cause some error. I'll have the library on the boost regression test thingy sometime next week and will look more into other compilers and OSX etc. then. 
But that gives me something to start with, so thank you!

**Comment by thumbidea** [comment]
I've just tested marton78's changes with Xcode 7. The inclusion of <boost/detail/utf8_codecvt_facet.ipp> results in duplicate symbols at link time for all of the members of utf8_codecvt_facet, since this header is meant to be included into a source file and not another header. One simple fix is to declare all of the methods inline:

```
--- ./boost/process/locale.hpp.orig	2017-01-07 11:32:20.000000000 -0500
+++ ./boost/process/locale.hpp	2017-01-07 11:30:57.000000000 -0500
@@ -21,7 +21,7 @@
 namespace boost { namespace process { namespace detail {
 
 #define BOOST_UTF8_END_NAMESPACE }}}
-#define BOOST_UTF8_DECL
+#define BOOST_UTF8_DECL inline
 
 #include <boost/detail/utf8_codecvt_facet.ipp>
 
```

However this exposes a bug in boost/detail/utf8_codecvt_facet.ipp, where two methods are not prefixed with BOOST_UTF8_DECL. I'm not sure how you'd want to deal with this since you'd either have to patch boost, or add a source file, since boost::process is 100% inline with no source files suitable for including boost/detail/utf8_codecvt_facet.ipp.

```
--- ./boost/detail/utf8_codecvt_facet.ipp.orig	2017-01-07 11:30:34.000000000 -0500
+++ ./boost/detail/utf8_codecvt_facet.ipp	2017-01-07 11:29:41.000000000 -0500
@@ -226,6 +226,7 @@
 namespace detail {
 
 template<std::size_t s>
+BOOST_UTF8_DECL
 int get_cont_octet_out_count_impl(wchar_t word){
     if (word < 0x80) {
         return 0;
@@ -237,6 +238,7 @@
 }
 
 template<>
+BOOST_UTF8_DECL
 int get_cont_octet_out_count_impl<4>(wchar_t word){
     if (word < 0x80) {
         return 0;
```

I'm happy to help test under Xcode 7 or 8 if needed.

**Comment by thumbidea** [comment]
Here's a better fix against marton78's original changeset.

This requires that anyone wanting to use this code on OS X must include <boost/process/utf8_codecvt_facet.ipp> in exactly on of their source files.

It requires no changes to boost, or additions of source files to boost::process.

```
--- boost/process/locale.hpp.orig	2017-01-07 11:32:20.000000000 -0500
+++ boost/process/locale.hpp	2017-01-07 11:54:59.000000000 -0500
@@ -23,7 +23,7 @@
 #define BOOST_UTF8_END_NAMESPACE }}}
 #define BOOST_UTF8_DECL
 
-#include <boost/detail/utf8_codecvt_facet.ipp>
+#include <boost/detail/utf8_codecvt_facet.hpp>
 
 #undef BOOST_UTF8_BEGIN_NAMESPACE
 #undef BOOST_UTF8_END_NAMESPACE
--- /dev/null	2017-01-07 11:59:57.000000000 -0500
+++ boost/process/utf8_codecvt_facet.ipp	2017-01-07 11:59:36.000000000 -0500
@@ -0,0 +1,28 @@
+// Copyright (c) 2016 Klemens D. Morgenstern
+// Copyright (c) 2008 Beman Dawes
+// Distributed under the Boost Software License, Version 1.0. (See accompanying
+// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
+
+#ifndef BOOST_PROCESS_UTF8_CODECVT_FACET_IPP_
+#define BOOST_PROCESS_UTF8_CODECVT_FACET_IPP_
+
+// NOTE: If using boost::process on OS X you must include this header in
+// exactly one of your source files.
+
+#ifdef __APPLE__
+
+#define BOOST_UTF8_BEGIN_NAMESPACE \
+namespace boost { namespace process { namespace detail {
+
+#define BOOST_UTF8_END_NAMESPACE }}}
+#define BOOST_UTF8_DECL
+
+#include <boost/detail/utf8_codecvt_facet.ipp>
+
+#undef BOOST_UTF8_BEGIN_NAMESPACE
+#undef BOOST_UTF8_END_NAMESPACE
+#undef BOOST_UTF8_DECL
+
+#endif /* __APPLE__ */
+
+#endif /* BOOST_PROCESS_UTF8_CODECVT_FACET_IPP_ */
```

Then at the end of one of my project's source files I add:

```
#ifdef __APPLE__
// Fix for missing std::utf8_codecvt_facet
#include <boost/process/utf8_codecvt_facet.ipp>
#endif
```

**Comment by klemens-morgenstern** [comment]
@thumbidea Thanks! I'll check this out as soon as I have a working test for OSX.

**Comment by klemens-morgenstern** [comment]
Alright, I finally got to do it, see 663fc69691afe2d5896ae354ef1069912c2beb5b. The `std::utf8_codecvt_facet` was a typo, I hope it works now using [`std::codecvt_utf8<wchar_t>`](http://en.cppreference.com/w/cpp/locale/codecvt_utf8).
Sadly I can'test this as of yet, so if one of you finds the time to do so, I'd be very grateful.

**Comment by marton78** [comment]
HI  @klemens-morgenstern, i checked your changes and they fix building on osx, barring two little oversights which I have commented in commit 663fc69.

**Comment by klemens-morgenstern** [comment]
Thanks, fixed that in 2a7f5bb.

**Comment by klemens-morgenstern** [comment]
Alrigh, I'm assuming that works now, so I'll close this PR. Feel free to reopen it if there are still issues on OSX.

**Pull request closed without merging**
