### PR TITLE
Set CLOEXEC on async_pipe descriptors

### LINKED ISSUE #153: On Linux spawning processes from multiple threads causes child process not to exit due to leaking file descriptors
I have this simple test code.

```cpp
#include <thread>
#include <iostream>
#include <vector>
#include <memory>
#include <boost/process.hpp>
#include <boost/test/unit_test.hpp>

static void boostProcessCat() {
  std::shared_ptr<boost::process::opstream> outPipe = std::make_shared<boost::process::opstream>();
  boost::process::child catProcess("cat -", boost::process::std_in < *outPipe);

  // Close pipe
  outPipe = nullptr;

  catProcess.wait();
  BOOST_CHECK_EQUAL(catProcess.exit_code(), 0);
}

BOOST_AUTO_TEST_CASE(boostProcessCatTest) {
  boostProcessCat();
}

BOOST_AUTO_TEST_CASE(boostProcessCatSimultaneousTest) {
  int nThreads = 1000;

  std::vector<std::thread> threads;
  threads.reserve(nThreads);

  for (int i = 0; i < nThreads; ++i) {
    threads.emplace_back(boostProcessCat);
  }

  for (int i = 0; i < nThreads; ++i) {
    if (threads[i].joinable()) {
      threads[i].join();
    }
  }
}
```

The function `boostProcessCat` opens `cat`, then closes its input pipe. Afterwards we wait for `cat` to exit. `cat` should exit because we closed its stdin pipe.
The test `boostProcessCatSimultaneousTest` spawns 1000 threads. Each of them just to call `boostProcessCat`. In this scenario the `cat` never exits. Note that calling `boostProcessCat` just once is OK.

The reason I decided to try Boost.Process is to circumvent this very same problem that I also encountered when trying to write a Linux process spawn function that opens pipes to child's stdio.
The problem is that there are leaking file descriptors across the call to some of the `exec` family functions. This is caused when two threads get to the point of `fork` at the same time. The Linux pipes were probably created without `FD_CLOEXEC` being set. This is of course desirable because we want the pipes to be open in the child process. After `fork` both child processes would have these pipes inherited, so they would leak.
Because this is a general purpose library, what needs to be done after `fork` is to close all other file descriptors, except those that are associated with the pipes we want. Somewhere I read that the Java virtual machine does it like that. I also can't see any other way of doing it. There is no POSIX function to get all file descriptors of a process. On Linux you can get them from `/proc/<pid>/fd`. I have read that this is not portable across all Linux variants.
If you are sure that in the parent process the only usage of `fork` is to afterwards `exec` another file, there is another option. Create the pipes with `FD_CLOEXEC` set. Then after the fork unset the flag before doing `exec`. Then only the pipe you want "leaks". This of course assumes also that in the parent process there are no other file descriptors open without `FD_CLOEXEC`. When I tried to do that I got some very nasty memory corruptions in the parent. When running with Valgrind could not reproduce the problem, no invalid memory reads/writes. Welcome to fork&threads hell :)

### PR DESCRIPTION
**Pull request by amerry**
Fixes #153.

### CODE REVIEW

**Comment by amerry** [comment]
While the CLOEXEC flag could be made optional, I don't really see the use case. And it wouldn't be cross-platform - handles are not inherited by default on Windows (you have to explicitly enable inheritance on the handle itself *and* enable handle inheritance when calling `CreateProcess`).

**Comment by amerry** [comment]
I'll look at the failures next week. I think the detection of pipe2 might be the issue.

**Comment by klemens-morgenstern** [comment]
I think this addresses the same issue as #92. I fear ths will cause unexpected behaviour, so I don't want `FD_CLOEXEC` to be the default.

**Comment by microcai** [comment]
> 

or you can just think that Windows have all handles CLOEXEC by default.

**Pull request closed without merging**
